-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 17:57:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema work_demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema work_demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `work_demo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `work_demo` ;

-- -----------------------------------------------------
-- Table `work_demo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_demo`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `work_demo`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_demo`.`customers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrh1g1a20omjmn6kurd35o3eit` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKrh1g1a20omjmn6kurd35o3eit`
    FOREIGN KEY (`user_id`)
    REFERENCES `work_demo`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `work_demo`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_demo`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `work_demo`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_demo`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME(6) NOT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKpxtb8awmi0dk6smoh2vp1litg` (`customer_id` ASC) VISIBLE,
  INDEX `FKkp5k52qtiygd8jkag4hayd0qg` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKkp5k52qtiygd8jkag4hayd0qg`
    FOREIGN KEY (`product_id`)
    REFERENCES `work_demo`.`products` (`id`),
  CONSTRAINT `FKpxtb8awmi0dk6smoh2vp1litg`
    FOREIGN KEY (`customer_id`)
    REFERENCES `work_demo`.`customers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
